name: Sync to CI_CD_Sample2

on:
  push:
    branches:
      - master  # or whatever branch you're tracking

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone target repo
        run: |
          git clone https://x-access-token:${{ secrets.NEWTOKEN2 }}@github.com/Sudhi2000/CI_CD_Sample2.git destination-repo
          
      - name: Copy files to target repo
        run: |
          rsync -av --delete --exclude '.git' ./ destination-repo/

      - name: Commit and Push changes to target repo
        run: |
          cd destination-repo
          git add .
          git commit -m "Auto-sync from Angular_deployment on ${{ github.sha }}" || echo "No changes to commit"
          git push origin main
